//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMatveevLesson5.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/WCFApp")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((this.UUIDField.Equals(value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://schemas.datacontract.org/2004/07/WCFApp")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UUID {
            get {
                return this.UUIDField;
            }
            set {
                if ((this.UUIDField.Equals(value) != true)) {
                    this.UUIDField = value;
                    this.RaisePropertyChanged("UUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Worker", Namespace="http://schemas.datacontract.org/2004/07/WCFApp")]
    [System.SerializableAttribute()]
    public partial struct Worker : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartamentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartamentId {
            get {
                return this.DepartamentIdField;
            }
            set {
                if ((this.DepartamentIdField.Equals(value) != true)) {
                    this.DepartamentIdField = value;
                    this.RaisePropertyChanged("DepartamentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/connectMessage", ReplyAction="http://tempuri.org/IService1/connectMessageResponse")]
        string connectMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/connectMessage", ReplyAction="http://tempuri.org/IService1/connectMessageResponse")]
        System.Threading.Tasks.Task<string> connectMessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEmployees", ReplyAction="http://tempuri.org/IService1/getEmployeesResponse")]
        System.Collections.Generic.List<VMatveevLesson5.ServiceReference.Employee> getEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEmployees", ReplyAction="http://tempuri.org/IService1/getEmployeesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<VMatveevLesson5.ServiceReference.Employee>> getEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEmployeesCount", ReplyAction="http://tempuri.org/IService1/getEmployeesCountResponse")]
        int getEmployeesCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEmployeesCount", ReplyAction="http://tempuri.org/IService1/getEmployeesCountResponse")]
        System.Threading.Tasks.Task<int> getEmployeesCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEmployee", ReplyAction="http://tempuri.org/IService1/getEmployeeResponse")]
        VMatveevLesson5.ServiceReference.Employee getEmployee(int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getEmployee", ReplyAction="http://tempuri.org/IService1/getEmployeeResponse")]
        System.Threading.Tasks.Task<VMatveevLesson5.ServiceReference.Employee> getEmployeeAsync(int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDepartaments", ReplyAction="http://tempuri.org/IService1/getDepartamentsResponse")]
        System.Collections.Generic.List<VMatveevLesson5.ServiceReference.Department> getDepartaments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDepartaments", ReplyAction="http://tempuri.org/IService1/getDepartamentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<VMatveevLesson5.ServiceReference.Department>> getDepartamentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDepartamentsCount", ReplyAction="http://tempuri.org/IService1/getDepartamentsCountResponse")]
        int getDepartamentsCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDepartamentsCount", ReplyAction="http://tempuri.org/IService1/getDepartamentsCountResponse")]
        System.Threading.Tasks.Task<int> getDepartamentsCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDepartament", ReplyAction="http://tempuri.org/IService1/getDepartamentResponse")]
        VMatveevLesson5.ServiceReference.Department getDepartament(int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDepartament", ReplyAction="http://tempuri.org/IService1/getDepartamentResponse")]
        System.Threading.Tasks.Task<VMatveevLesson5.ServiceReference.Department> getDepartamentAsync(int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getWorkers", ReplyAction="http://tempuri.org/IService1/getWorkersResponse")]
        System.Collections.Generic.List<VMatveevLesson5.ServiceReference.Worker> getWorkers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getWorkers", ReplyAction="http://tempuri.org/IService1/getWorkersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<VMatveevLesson5.ServiceReference.Worker>> getWorkersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : VMatveevLesson5.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<VMatveevLesson5.ServiceReference.IService1>, VMatveevLesson5.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string connectMessage() {
            return base.Channel.connectMessage();
        }
        
        public System.Threading.Tasks.Task<string> connectMessageAsync() {
            return base.Channel.connectMessageAsync();
        }
        
        public System.Collections.Generic.List<VMatveevLesson5.ServiceReference.Employee> getEmployees() {
            return base.Channel.getEmployees();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<VMatveevLesson5.ServiceReference.Employee>> getEmployeesAsync() {
            return base.Channel.getEmployeesAsync();
        }
        
        public int getEmployeesCount() {
            return base.Channel.getEmployeesCount();
        }
        
        public System.Threading.Tasks.Task<int> getEmployeesCountAsync() {
            return base.Channel.getEmployeesCountAsync();
        }
        
        public VMatveevLesson5.ServiceReference.Employee getEmployee(int index) {
            return base.Channel.getEmployee(index);
        }
        
        public System.Threading.Tasks.Task<VMatveevLesson5.ServiceReference.Employee> getEmployeeAsync(int index) {
            return base.Channel.getEmployeeAsync(index);
        }
        
        public System.Collections.Generic.List<VMatveevLesson5.ServiceReference.Department> getDepartaments() {
            return base.Channel.getDepartaments();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<VMatveevLesson5.ServiceReference.Department>> getDepartamentsAsync() {
            return base.Channel.getDepartamentsAsync();
        }
        
        public int getDepartamentsCount() {
            return base.Channel.getDepartamentsCount();
        }
        
        public System.Threading.Tasks.Task<int> getDepartamentsCountAsync() {
            return base.Channel.getDepartamentsCountAsync();
        }
        
        public VMatveevLesson5.ServiceReference.Department getDepartament(int index) {
            return base.Channel.getDepartament(index);
        }
        
        public System.Threading.Tasks.Task<VMatveevLesson5.ServiceReference.Department> getDepartamentAsync(int index) {
            return base.Channel.getDepartamentAsync(index);
        }
        
        public System.Collections.Generic.List<VMatveevLesson5.ServiceReference.Worker> getWorkers() {
            return base.Channel.getWorkers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<VMatveevLesson5.ServiceReference.Worker>> getWorkersAsync() {
            return base.Channel.getWorkersAsync();
        }
    }
}
